#!/usr/bin/env python3
"""features/docs-experience V97 — the contextual help-link registry.

`features/docs-experience/inventory/help-links.json` maps a stable KEY to a docs path. Product code holds keys, never URLs,
so a domain move (.run → .com → .dev) or a page move touches this file only.

  gen_help_links.py            validate the registry (every path resolves to a page, every #anchor to a heading)
  gen_help_links.py --write    also regenerate the per-product mirrors in the sibling checkouts
  gen_help_links.py --check    fail if a sibling checkout's mirror differs from the registry (the product repos' PRs must be re-synced)

Mirrors (each holds only its own surface's keys):
  dashboard -> $VHB_CLIENT/src/utils/helpLinks.generated.ts          (default ~/Desktop/works/vhb-client)
  desktop   -> $BEAVER_DESKTOP/apps/desktop/src/lib/helpLinks.generated.ts   (default ~/Desktop/vhb/beaver-desktop)
  cli       -> $BEAVER_CLI/helplinks/helplinks.generated.go           (default ~/Desktop/vhb/beaver-cli)
"""
import json, os, re, sys

ROOT = os.environ.get("DOCS_ROOT") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REG = f"{ROOT}/features/docs-experience/inventory/help-links.json"
HOME = os.path.expanduser("~")
MIRRORS = {
    "dashboard": (os.environ.get("VHB_CLIENT", f"{HOME}/Desktop/works/vhb-client"), "src/utils/helpLinks.generated.ts", "ts"),
    "desktop": (os.environ.get("BEAVER_DESKTOP", f"{HOME}/Desktop/vhb/beaver-desktop"), "apps/desktop/src/lib/helpLinks.generated.ts", "ts"),
    "cli": (os.environ.get("BEAVER_CLI", f"{HOME}/Desktop/vhb/beaver-cli"), "helplinks/helplinks.generated.go", "go"),
}
KEY = re.compile(r"^(dashboard|desktop|cli)(\.[a-z0-9-]+)+$")


def slug(h):
    h = re.sub(r"[`*_]", "", h).strip().lower()
    h = re.sub(r"[^\w\s-]", "", h)
    return re.sub(r"\s+", "-", h)


def page_file(path):
    p = path.lstrip("/")
    for c in (f"{ROOT}/{p}.mdx", f"{ROOT}/{p}/index.mdx"):
        if os.path.exists(c):
            return c
    return None


def validate(reg):
    errs = []
    if not reg["base"].startswith("https://"):
        errs.append("base must be https")
    for key, v in sorted(reg["keys"].items()):
        if not KEY.match(key):
            errs.append(f"{key}: key must look like <dashboard|desktop|cli>.<area>[.<state>]")
        if v.get("surface") != key.split(".")[0]:
            errs.append(f"{key}: surface {v.get('surface')!r} does not match the key prefix")
        path, _, anchor = v["path"].partition("#")
        f = page_file(path)
        if not path.startswith("/"):
            errs.append(f"{key}: path must start with /")
        elif not f:
            errs.append(f"{key}: no page at {path}")
        elif anchor:
            heads = {slug(m.group(1)) for m in re.finditer(r"^#{2,4}\s+(.+?)\s*$", open(f).read(), re.M)}
            if anchor not in heads:
                errs.append(f"{key}: no heading #{anchor} in {path}")
        if not v.get("where"):
            errs.append(f"{key}: `where` (the product spot it serves) is required")
    return errs


def render_ts(reg, surface):
    rows = {k: v["path"] for k, v in sorted(reg["keys"].items()) if v["surface"] == surface}
    body = ",\n".join(f'  {json.dumps(k)}: {json.dumps(p)}' for k, p in rows.items())
    return (f"// GENERATED FILE — do not edit. Source: mintlify/features/docs-experience/inventory/help-links.json (scripts/gen_help_links.py).\n"
            f"// Keys, not URLs, live in product code; the base address and page paths change in the registry only.\n"
            f"export const DOCS_BASE_URL = {json.dumps(reg['base'])};\n\n"
            f"export const HELP_LINKS = {{\n{body},\n}} as const;\n\nexport type HelpKey = keyof typeof HELP_LINKS;\n")


def render_go(reg, surface):
    rows = {k: v["path"] for k, v in sorted(reg["keys"].items()) if v["surface"] == surface}
    w = max(len(json.dumps(k)) for k in rows) + 1  # gofmt aligns the values of a map literal
    body = "\n".join(f'\t{(json.dumps(k) + ":").ljust(w)} {json.dumps(p)},' for k, p in rows.items())
    return ("// Code generated by mintlify/scripts/gen_help_links.py from features/docs-experience/inventory/help-links.json. DO NOT EDIT.\n\n"
            "package helplinks\n\n"
            f"// BaseURL is the docs site's address; it changes in the registry only.\nconst BaseURL = {json.dumps(reg['base'])}\n\n"
            f"var links = map[string]string{{\n{body}\n}}\n")


def main():
    reg = json.load(open(REG))
    errs = validate(reg)
    for e in errs:
        print("ERROR  help-links:", e)
    write, check = "--write" in sys.argv, "--check" in sys.argv
    if write or check:
        for surface, (repo, rel, kind) in MIRRORS.items():
            if not os.path.isdir(repo):
                print(f"skip   {surface}: {repo} not checked out")
                continue
            want = (render_ts if kind == "ts" else render_go)(reg, surface)
            dest = f"{repo}/{rel}"
            have = open(dest).read() if os.path.exists(dest) else None
            if write and have != want:
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                open(dest, "w").write(want)
                print(f"wrote  {dest}")
            elif check and have != want:
                errs.append(f"{surface} mirror {dest} is out of date — run `python3 scripts/gen_help_links.py --write` and commit it in that repo")
                print("ERROR  help-links:", errs[-1])
    print(f"{len(reg['keys'])} help-link keys · {len(errs)} errors")
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
